version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db-init/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DB_DEV}, ${DB_TEST}
volumes:
  postgres:
    
